# Generated by Django 4.0.6 on 2022-07-10 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_project_blog_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_blog',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
