# Generated by Django 4.0.6 on 2022-07-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_project_blog_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_blog',
            new_name='Blog',
        ),
    ]
